name: Thundra Foresight

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v2
        with:
          distribution: "adopt"
          java-version: "8"
      - name: Thundra Maven Test Instrumentation
        uses: thundra-io/thundra-maven-test-action@v1
        with:
          apikey: ${{ secrets.THUNDRA_APIKEY }}
          project_id: ${{ secrets.THUNDRA_PROJECT_ID }}
          command: mvn clean install
        env:
          THUNDRA_AGENT_REPORT_REST_BASEURL: https://collector.thundra.us/v1
